# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a919aaea9b859baa685f53dbcd445649464870e7b5dcdc4c0bea0c9dd4dde684b87a0d23ed0c1234e8a79eea5fea2a612c776b6fae83f5845c28dbbd8523dc

test:
  secret_key_base: 72e3fac4c5c28e31575ba65d99af771c84c34cc1698d5454e3c8041b92b4884a629a7ee6387e24d31504e24f18e6880ac3f1227f6376466c4d0e5e24c8dbcd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
